# -*- coding: utf-8 -*-
"""IE 442 HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbjBQOd4gCz2AnjdGFtgT-eIC1dSLCSk
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from alpha_vantage.timeseries import TimeSeries

# API Setup
API_key = "AW25HH4Y84OJ93V6"
ts = TimeSeries(key=API_key, output_format="pandas")

# Title of the app
st.title("Stock Price Analysis")

# Sidebar for user input (stock symbol and date range)
st.sidebar.title("Stock Data Input")
ticker = st.sidebar.text_input("Enter Stock Ticker", value="MSFT")
start_date = st.sidebar.date_input("Start Date")
end_date = st.sidebar.date_input("End Date")

# Fetch stock data from Alpha Vantage API
try:
    data, meta_data = ts.get_monthly_adjusted(symbol=ticker)
    data = pd.DataFrame(data)

    # Filter data by user input date range
    data.index = pd.to_datetime(data.index)
    data = data[(data.index >= pd.to_datetime(start_date)) & (data.index <= pd.to_datetime(end_date))]

    # Plot the stock data
    st.write(f"### {ticker} Stock Price from {start_date} to {end_date}")
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(data.index, data["5. adjusted close"], label=f"{ticker} Adjusted Close Price")
    ax.set_xlabel("Date")
    ax.set_ylabel("Price (USD)")
    ax.set_title(f"{ticker} Stock Price Over Time")
    ax.legend()
    st.pyplot(fig)

except Exception as e:
    st.error(f"Error fetching data for {ticker}: {str(e)}")