# -*- coding: utf-8 -*-
"""Stockipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbjBQOd4gCz2AnjdGFtgT-eIC1dSLCSk
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px

st.title("Stock Dashboard")
ticker = st.text_input("Enter a ticker symbol", "AAPL")
start_date = st.date_input("Start date", value=pd.to_datetime("2022-01-01"))
end_date = st.date_input("End date", value=pd.to_datetime("today"))